/**
 * Canvas 模板 4
 * 
 * 自动从 1 (4).pptx 提取生成
 * 
 * 画布尺寸: 1080 × 1920 px
 */

import { type SlideTemplate, type TemplateElement } from "./testimonial-template";

export const canvas_template_4Template: SlideTemplate = {
    id: 'canvas-template-4',
    name: 'Canvas 模板 4',
    description: '从 Canvas 设计自动提取的模板',
    category: 'testimonial',
    size: {
        width: 1080,
        height: 1920,
    },

    elements: [
        {
            id: 'image-1',
            type: 'background',
            slot: 'background-image',
            position: { x: 0, y: 0 },
            size: { width: 1080, height: 1920 },
            style: { objectFit: 'cover', zIndex: 1 },
            optional: false,
        },
        {
            id: 'image-2',
            type: 'background',
            slot: 'main-image',
            position: { x: 3, y: 831 },
            size: { width: 1077, height: 1077 },
            style: { objectFit: 'cover', zIndex: 2, borderRadius: 538 },
            optional: false,
        },
        {
            id: 'bg-3',
            type: 'background',
            slot: 'decoration-3',
            position: { x: 0, y: 0 },
            size: { width: 189, height: 237 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.70)', zIndex: 3 },
            optional: false,
        },
        {
            id: 'text-4',
            type: 'text',
            slot: 'text-textbox-6',
            position: { x: 0, y: -4 },
            size: { width: 189, height: 241 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 4 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'bg-5',
            type: 'background',
            slot: 'decoration-5',
            position: { x: 0, y: 0 },
            size: { width: 163, height: 164 },
            style: { backgroundColor: '#FFFFFF', zIndex: 5 },
            optional: false,
        },
        {
            id: 'text-6',
            type: 'text',
            slot: 'text-textbox-9',
            position: { x: 0, y: -4 },
            size: { width: 163, height: 168 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 6 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'text-7',
            type: 'text',
            slot: 'text-textbox-11',
            position: { x: 79, y: -7 },
            size: { width: 456, height: 79 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#000000', textAlign: 'center', zIndex: 7 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Isabel Mercado',
            optional: false,
        },
        {
            id: 'bg-8',
            type: 'background',
            slot: 'decoration-8',
            position: { x: 0, y: 33 },
            size: { width: 59, height: 0 },
            style: { backgroundColor: '#000000', zIndex: 8 },
            optional: false,
        },
        {
            id: 'image-9',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 294, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 9, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-10',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 404, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 10, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-11',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 513, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 11, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-12',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 623, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 12, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-13',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 732, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 13, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'text-14',
            type: 'text',
            slot: 'review',
            position: { x: 276, y: 644 },
            size: { width: 527, height: 528 },
            style: { fontSize: 32, fontFamily: 'Canva Sans Italics', color: '#000000', textAlign: 'center', zIndex: 14 },
            constraints: { maxChars: 404, overflowStrategy: 'auto-scale' },
            exampleContent: '“I’m beyond impressed! My skin feels incredibly soft and hydrated, and I've noticed a visible reduct',
            optional: false,
        },
        {
            id: 'text-15',
            type: 'text',
            slot: 'social',
            position: { x: 311, y: 1751 },
            size: { width: 457, height: 61 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#FFFFFF', textAlign: 'center', zIndex: 15 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: '@reallygreatsite',
            optional: false,
        },
        {
            id: 'bg-16',
            type: 'background',
            slot: 'decoration-16',
            position: { x: 0, y: 0 },
            size: { width: 189, height: 237 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.70)', zIndex: 16 },
            optional: false,
        },
        {
            id: 'text-17',
            type: 'text',
            slot: 'text-textbox-6',
            position: { x: 0, y: -4 },
            size: { width: 189, height: 241 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 17 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'bg-18',
            type: 'background',
            slot: 'decoration-18',
            position: { x: 0, y: 0 },
            size: { width: 163, height: 164 },
            style: { backgroundColor: '#FFFFFF', zIndex: 18 },
            optional: false,
        },
        {
            id: 'text-19',
            type: 'text',
            slot: 'text-textbox-9',
            position: { x: 0, y: -4 },
            size: { width: 163, height: 168 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 19 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'text-20',
            type: 'text',
            slot: 'text-textbox-11',
            position: { x: 79, y: -7 },
            size: { width: 456, height: 79 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#000000', textAlign: 'center', zIndex: 20 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Isabel Mercado',
            optional: false,
        },
        {
            id: 'bg-21',
            type: 'background',
            slot: 'decoration-21',
            position: { x: 0, y: 33 },
            size: { width: 59, height: 0 },
            style: { backgroundColor: '#000000', zIndex: 21 },
            optional: false,
        },
        {
            id: 'image-1',
            type: 'background',
            slot: 'background-image',
            position: { x: 0, y: 0 },
            size: { width: 1080, height: 1920 },
            style: { objectFit: 'cover', zIndex: 1 },
            optional: false,
        },
        {
            id: 'image-2',
            type: 'background',
            slot: 'main-image',
            position: { x: 3, y: 831 },
            size: { width: 1077, height: 1077 },
            style: { objectFit: 'cover', zIndex: 2, borderRadius: 538 },
            optional: false,
        },
        {
            id: 'bg-3',
            type: 'background',
            slot: 'decoration-3',
            position: { x: 0, y: 0 },
            size: { width: 189, height: 237 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.70)', zIndex: 3 },
            optional: false,
        },
        {
            id: 'text-4',
            type: 'text',
            slot: 'text-textbox-6',
            position: { x: 0, y: -4 },
            size: { width: 189, height: 241 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 4 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'bg-5',
            type: 'background',
            slot: 'decoration-5',
            position: { x: 0, y: 0 },
            size: { width: 163, height: 164 },
            style: { backgroundColor: '#FFFFFF', zIndex: 5 },
            optional: false,
        },
        {
            id: 'text-6',
            type: 'text',
            slot: 'text-textbox-9',
            position: { x: 0, y: -4 },
            size: { width: 163, height: 168 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 6 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'text-7',
            type: 'text',
            slot: 'text-textbox-11',
            position: { x: 79, y: -7 },
            size: { width: 456, height: 79 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#000000', textAlign: 'center', zIndex: 7 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Isabel Mercado',
            optional: false,
        },
        {
            id: 'bg-8',
            type: 'background',
            slot: 'decoration-8',
            position: { x: 0, y: 33 },
            size: { width: 59, height: 0 },
            style: { backgroundColor: '#000000', zIndex: 8 },
            optional: false,
        },
        {
            id: 'image-9',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 294, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 9, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-10',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 404, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 10, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-11',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 513, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 11, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-12',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 623, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 12, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'image-13',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 732, y: 415 },
            size: { width: 54, height: 51 },
            style: { objectFit: 'cover', zIndex: 13, borderRadius: 27 },
            optional: false,
        },
        {
            id: 'text-14',
            type: 'text',
            slot: 'review',
            position: { x: 276, y: 644 },
            size: { width: 527, height: 528 },
            style: { fontSize: 32, fontFamily: 'Canva Sans Italics', color: '#000000', textAlign: 'center', zIndex: 14 },
            constraints: { maxChars: 404, overflowStrategy: 'auto-scale' },
            exampleContent: '“I’m beyond impressed! My skin feels incredibly soft and hydrated, and I've noticed a visible reduct',
            optional: false,
        },
        {
            id: 'text-15',
            type: 'text',
            slot: 'social',
            position: { x: 311, y: 1751 },
            size: { width: 457, height: 61 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#FFFFFF', textAlign: 'center', zIndex: 15 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: '@reallygreatsite',
            optional: false,
        },
        {
            id: 'bg-16',
            type: 'background',
            slot: 'decoration-16',
            position: { x: 0, y: 0 },
            size: { width: 189, height: 237 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.70)', zIndex: 16 },
            optional: false,
        },
        {
            id: 'text-17',
            type: 'text',
            slot: 'text-textbox-6',
            position: { x: 0, y: -4 },
            size: { width: 189, height: 241 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 17 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'bg-18',
            type: 'background',
            slot: 'decoration-18',
            position: { x: 0, y: 0 },
            size: { width: 163, height: 164 },
            style: { backgroundColor: '#FFFFFF', zIndex: 18 },
            optional: false,
        },
        {
            id: 'text-19',
            type: 'text',
            slot: 'text-textbox-9',
            position: { x: 0, y: -4 },
            size: { width: 163, height: 168 },
            style: { fontSize: 18, fontFamily: 'Arial', color: '#000000', textAlign: 'center', zIndex: 19 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Example text',
            optional: false,
        },
        {
            id: 'text-20',
            type: 'text',
            slot: 'text-textbox-11',
            position: { x: 79, y: -7 },
            size: { width: 456, height: 79 },
            style: { fontSize: 33, fontFamily: 'Canva Sans', color: '#000000', textAlign: 'center', zIndex: 20 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Isabel Mercado',
            optional: false,
        },
        {
            id: 'bg-21',
            type: 'background',
            slot: 'decoration-21',
            position: { x: 0, y: 33 },
            size: { width: 59, height: 0 },
            style: { backgroundColor: '#000000', zIndex: 21 },
            optional: false,
        },
    ],

    // AI 生成提示
    aiPromptHints: [
        '使用 <TEMPLATE template="canvas-template-4"> 标签来生成幻灯片',
        '填充所有 slot 对应的内容',
    ],
};

export default canvas_template_4Template;
