/**
 * Canvas 模板 1
 * 
 * 自动从 1 (1).pptx 提取生成
 * 
 * 画布尺寸: 1080 × 1080 px
 */

import { type SlideTemplate, type TemplateElement } from "./testimonial-template";

export const canvas_template_1Template: SlideTemplate = {
    id: 'canvas-template-1',
    name: 'Canvas 模板 1',
    description: '从 Canvas 设计自动提取的模板',
    category: 'testimonial',
    size: {
        width: 1080,
        height: 1080,
    },

    elements: [
        {
            id: 'image-1',
            type: 'background',
            slot: 'background-image',
            position: { x: 0, y: 0 },
            size: { width: 1080, height: 1080 },
            style: { objectFit: 'cover', zIndex: 1, borderRadius: 540 },
            optional: false,
        },
        {
            id: 'bg-2',
            type: 'background',
            slot: 'decoration-2',
            position: { x: 0, y: 0 },
            size: { width: 201, height: 101 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.85)', zIndex: 2 },
            optional: false,
        },
        {
            id: 'image-3',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 531, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 3, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-4',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 595, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 4, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-5',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 663, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 5, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-6',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 733, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 6, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-7',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 809, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 7, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-8',
            type: 'image',
            slot: 'main-image',
            position: { x: 0, y: 0 },
            size: { width: 667, height: 667 },
            style: { objectFit: 'cover', zIndex: 8, borderRadius: 333 },
            optional: false,
        },
        {
            id: 'text-9',
            type: 'text',
            slot: 'review',
            position: { x: 445, y: 534 },
            size: { width: 499, height: 128 },
            style: { fontSize: 23, fontFamily: 'Proxima Nova', color: '#000000', textAlign: 'center', zIndex: 9 },
            constraints: { maxChars: 162, overflowStrategy: 'auto-scale' },
            exampleContent: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec magna leo."',
            optional: false,
        },
        {
            id: 'text-10',
            type: 'text',
            slot: 'title',
            position: { x: 177, y: 829 },
            size: { width: 482, height: 68 },
            style: { fontSize: 39, fontFamily: 'Amsterdam One', color: '#FFFFFF', textAlign: 'center', zIndex: 10 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Review Product',
            optional: false,
        },
        {
            id: 'text-11',
            type: 'text',
            slot: 'social',
            position: { x: 199, y: 901 },
            size: { width: 493, height: 72 },
            style: { fontSize: 38, fontFamily: 'Canva Student Font', color: '#FFFFFF', textAlign: 'center', zIndex: 11 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: '@reallygreatsite',
            optional: false,
        },
        {
            id: 'bg-12',
            type: 'background',
            slot: 'decoration-12',
            position: { x: 0, y: 0 },
            size: { width: 201, height: 101 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.85)', zIndex: 12 },
            optional: false,
        },
        {
            id: 'image-13',
            type: 'image',
            slot: 'main-image',
            position: { x: 0, y: 0 },
            size: { width: 667, height: 667 },
            style: { objectFit: 'cover', zIndex: 13, borderRadius: 333 },
            optional: false,
        },
        {
            id: 'image-1',
            type: 'background',
            slot: 'background-image',
            position: { x: 0, y: 0 },
            size: { width: 1080, height: 1080 },
            style: { objectFit: 'cover', zIndex: 1, borderRadius: 540 },
            optional: false,
        },
        {
            id: 'bg-2',
            type: 'background',
            slot: 'decoration-2',
            position: { x: 0, y: 0 },
            size: { width: 201, height: 101 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.85)', zIndex: 2 },
            optional: false,
        },
        {
            id: 'image-3',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 531, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 3, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-4',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 595, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 4, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-5',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 663, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 5, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-6',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 733, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 6, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-7',
            type: 'image',
            slot: 'avatar-image',
            position: { x: 809, y: 460 },
            size: { width: 49, height: 47 },
            style: { objectFit: 'cover', zIndex: 7, borderRadius: 24 },
            optional: false,
        },
        {
            id: 'image-8',
            type: 'image',
            slot: 'main-image',
            position: { x: 0, y: 0 },
            size: { width: 667, height: 667 },
            style: { objectFit: 'cover', zIndex: 8, borderRadius: 333 },
            optional: false,
        },
        {
            id: 'text-9',
            type: 'text',
            slot: 'review',
            position: { x: 445, y: 534 },
            size: { width: 499, height: 128 },
            style: { fontSize: 23, fontFamily: 'Proxima Nova', color: '#000000', textAlign: 'center', zIndex: 9 },
            constraints: { maxChars: 162, overflowStrategy: 'auto-scale' },
            exampleContent: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec magna leo."',
            optional: false,
        },
        {
            id: 'text-10',
            type: 'text',
            slot: 'title',
            position: { x: 177, y: 829 },
            size: { width: 482, height: 68 },
            style: { fontSize: 39, fontFamily: 'Amsterdam One', color: '#FFFFFF', textAlign: 'center', zIndex: 10 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: 'Review Product',
            optional: false,
        },
        {
            id: 'text-11',
            type: 'text',
            slot: 'social',
            position: { x: 199, y: 901 },
            size: { width: 493, height: 72 },
            style: { fontSize: 38, fontFamily: 'Canva Student Font', color: '#FFFFFF', textAlign: 'center', zIndex: 11 },
            constraints: { maxChars: 50, overflowStrategy: 'auto-scale' },
            exampleContent: '@reallygreatsite',
            optional: false,
        },
        {
            id: 'bg-12',
            type: 'background',
            slot: 'decoration-12',
            position: { x: 0, y: 0 },
            size: { width: 201, height: 101 },
            style: { backgroundColor: 'rgba(255, 255, 255, 0.85)', zIndex: 12 },
            optional: false,
        },
        {
            id: 'image-13',
            type: 'image',
            slot: 'main-image',
            position: { x: 0, y: 0 },
            size: { width: 667, height: 667 },
            style: { objectFit: 'cover', zIndex: 13, borderRadius: 333 },
            optional: false,
        },
    ],

    // AI 生成提示
    aiPromptHints: [
        '使用 <TEMPLATE template="canvas-template-1"> 标签来生成幻灯片',
        '填充所有 slot 对应的内容',
    ],
};

export default canvas_template_1Template;
